### PR TITLE
add custom template url support

### PR DESCRIPTION
**Pull request by fearoffish**
Only tested with bitbucket URL's as of now

### CODE REVIEW

**Comment by jhunt** [comment]
Why not just set a `url` variable and test it for `-z` rather than  mucking about with `custom_url`?

**Comment by fearoffish** [comment]
No reason. That would be a more elegant solution.

**Comment by fearoffish** [comment]
Also, turns out that running `make manifest` later fails, as it checks the index...which knows nothing about the custom template.

**Comment by jhunt** [comment]
Also, also, turns out that @fearoffish likes to confuse issues, and the index problem he was running into was unrelated. ^_^

**Comment by fearoffish** [comment]
Also, also, also, turns out @jhunt is correct. Make sure you don't have 'track' as your version in the release you're using if it isn't in the index.

**Comment by jhunt** [comment]
Waiting on new commits before merging.

**Pull request closed without merging**
