### PR TITLE
Rename genesis -> denissis

### PR DESCRIPTION
**Pull request by jhunt**
Since Dennis has done such a fantastic job on this project, I vote we name it after him.

```
denissis init -k concourse
denissis new buffalo-lab
denissis deploy buffalo-lab
```

Think about it.

### CODE REVIEW

**Comment by Proplex** [comment]
LGTM, I say we merge this && rebase the history starting from this commit.

**Comment by patrick1378** [comment]
I've had a fork of genesis called Phil Collins for months now. The joke will be lost with this refactor and I'll be a bit miffed if we decide to go with this.

**Comment by daviddob** [comment]
LGTM, glad to see we are taking things in a new direction

**Comment by jhunt** [comment]
Somehow I don't think that's in the air... tonight, @patrick1378

**Comment by aanelli** [comment]
you think the Vatican will give us that sweet denesis.va domain?

**Comment by jhunt** [comment]
An idea ahead of its time I fear.  Closing, WONTMERGE.

**Comment by Proplex** [comment]
Closed with no comment?

**Pull request closed without merging**
