### PR TITLE
Check bosh environment that genesis uses so it errors better and faster

### PR DESCRIPTION
**Pull request by xiujiao**
This fix issue # 167.

Passed `make test` and tested it on bosh-lite deployment.

### CODE REVIEW

**Comment by xiujiao** [comment]
Please do not merge yet, found a bug when run `genesis vault-policies`

**Comment by xiujiao** [comment]
Remove `bosh env` command output, so `genesis vault-policies` will only print out vault policies. Now it is ready to review again.

**Comment by jhunt** [comment]
Is this something that can wait for @dennisjbell to get back from vacation to review?  He is far more familiar with the Genesis v2 codebase than I.

**Comment by xiujiao** [comment]
@jhunt yeah, it can wait :)

**Comment by jhunt** [comment]
@dennisjbell ^^

**Pull request merged**
